@startuml
'https://plantuml.com/deployment-diagram

legend
    Objects there can exist
    many instances of run-time
    are marked with green.
end legend

node "Client" as client_1 #ADA {
    agent "User interface" as ui_1
    agent "GameObserver" as mirror_1
    agent "API connector" as connector_1
    agent "Receiver" as listener_1

    ui_1 --> connector_1
    ui_1 <--> mirror_1
    mirror_1 <-down-> connector_1
    listener_1 -up-> mirror_1
}

node "Client" as client_2 #ADA {
    agent "User interface" as ui_2
    agent "GameObserver" as mirror_2
    agent "API connector" as connector_2
    agent "Receiver" as listener_2

    ui_2 --> connector_2
    ui_2 <--> mirror_2
    mirror_2 <-down-> connector_2
    listener_2 -up-> mirror_2
}

node "Client" as client_0 #ADA {
    agent "User interface" as ui_0
    agent "GameObserver" as mirror_0
    agent "API connector" as connector_0
    agent "Receiver" as listener_0

    ui_0 --> connector_0
    ui_0 <--> mirror_0
    mirror_0 <-down-> connector_0
    listener_0 -up-> mirror_0
}

database "Firebase Storage" as firebase

node "Server" as server {
    agent "API endpoint" as endpoint
    agent "Broadcaster" as broadcaster_0 #ADA
    agent "Broadcaster" as broadcaster_1 #ADA
    agent "Storage API" as storage
    agent "Lobby" as lobby_0 #ADA
    agent "Lobby" as lobby_1 #ADA
    agent "Orchestrator" as orchestrator
    agent "Router" as router

    firebase -up-> storage
    endpoint -[hidden]right- broadcaster_0
    broadcaster_0 -[hidden]right- broadcaster_1
    broadcaster_1 -[hidden]right- storage
    lobby_0 -up-> broadcaster_0
    lobby_0 -[hidden]right- lobby_1
    lobby_0 <-up- storage
    lobby_1 -up-> broadcaster_1
    lobby_1 <-up- storage
    orchestrator <-up- endpoint
    orchestrator .up.> endpoint
    router <-up- endpoint
    router .up.> endpoint
    router -up-> lobby_0
    router <.up. lobby_0
    router -up-> lobby_1
    router <.up. lobby_1
}



'client_1 -[hidden]down- server

endpoint <-up- connector_0
endpoint .up.> connector_0
endpoint <-up- connector_1
endpoint .up.> connector_1
endpoint <-up- connector_2
endpoint .up.> connector_2

broadcaster_0 -up-> listener_0
broadcaster_1 -up-> listener_1
broadcaster_1 -[hidden]up-> listener_1
broadcaster_1 -up-> listener_2

@enduml