@startuml
'https://plantuml.com/component-diagram

package "Server" {
    component "API endpoint" as api
    component "Broadcaster" as broadcaster
    component "Instance" as instance
    component "Orchestrator" as orchestrator
    component "Storage API" as storage

    orchestrator -up-> api
    orchestrator -up-> instance
    orchestrator -up-> storage
    instance -[hidden]up-> api
    instance -up-> broadcaster
    instance -[hidden]up-> storage
}

package "Client" {
    component "Event handler" as event
    component "Game controller" as controller
    component "Model mirror" as model
    component "Receiver" as receiver
    component "Transmitter" as transmitter
    component "Visualization" as visualization
    component "User interface" as ui

    controller -down-> visualization
    controller -down-> transmitter
    visualization -[hidden]down-> receiver
    visualization -down-> event
    visualization -down-> ui
    visualization -down-> model
    event -[hidden]-> model
    event -[hidden]-> receiver
    event -[hidden]-> transmitter
    ui -[hidden]-> model
    ui -[hidden]-> receiver
    ui -[hidden]-> transmitter
    model -[hidden]-> transmitter
    model --> receiver
}

receiver --> api
receiver --> broadcaster
transmitter --> api

@enduml