@startuml
'https://plantuml.com/component-diagram

package "Server" {
    component "API endpoint" as endpoint
    component "Broadcaster" as broadcaster
    component "Instance" as instance
    component "Orchestrator" as orchestrator
    component "Storage API" as storage

    orchestrator -up-> endpoint
    orchestrator -up-> instance
    orchestrator -up-> storage
    instance -[hidden]up-> endpoint
    instance -up-> broadcaster
    instance -[hidden]up-> storage
}

package "Client" {
    component "Event handler" as event
    component "Game controller" as controller
    component "Model mirror" as model
    component "Receiver" as receiver
    component "API connector" as connector
    component "Visualization" as visualization
    component "User interface" as ui

    controller -down-> visualization
    controller -down-> connector
    visualization -[hidden]down-> receiver
    visualization -down-> event
    visualization -down-> ui
    visualization -down-> model
    event -[hidden]-> model
    event -[hidden]-> receiver
    event -[hidden]-> connector
    ui -[hidden]-> model
    ui -[hidden]-> receiver
    ui -[hidden]-> connector
    model -[hidden]-> connector
    model --> receiver
}

receiver --> broadcaster
connector --> endpoint

@enduml