@startditaa
'https://plantuml.com/ditaa

Client layers
+-----------+-----------+
|           |           |
|   Types   |   States  |      View
|           |           |
+-----------+-----------+
|                       |
|         Utils         |    Utility
|                       |
+------------+----------+
|            |          |
| API client | Receiver |  Communication
|            |          |
+------------+----------+

Server layers
+--------------------+---------------------+\
|                                          ||
|               Orchestrator               ||
|                                          ||
+------------------------------------------+| Server logic
|                                          ||
|                   Lobby                  ||
|                                          ||
+------------------------------------------+/
|                                          |
|                  Router                  | Traffic routing
|                                          |
+--------------+-------------+-------------+
|              |             |             |
| API endpoint | Broadcaster | Storage API |  Communication
|              |             |             |
+--------------+-------------+-------------+

@endditaa