@startditaa
'https://plantuml.com/ditaa

Legend
/----\
|cE99| Model
\----/
/----\
|cADA| View
\----/
/----\
|c9CF|Controller
\----/
/----\
|    | Other
\----/

Client layers
+--------------------------------+
|c9CF                            |
|         Game controller        | Controller
|                                |
+--------------------------------+
|cADA                            |
|           Visualizer           |    View
|                                |
+---------------+----------------+
|cADA           |cADA            |
| Event handler | User interface |  Device UI
|               |                |
+---------------+----------------+
|cE99                            |
|          Model mirror          | Client logic
|                                |
+------------------+-------------+
|                  |             |
|   API connector  |   Listener  | Communication
|                  |             |
+------------------+-------------+

Server layers v1
+-----------------------------------------------+
|                                               |
|                                               | Traffic routing
|                                               |
+----------+----------+----------+ Orchestrator |
|cE99      |cE99      |cE99      |              |
| Instance | Instance | Instance |              |  Server logic
|          |          |          |              |
+----------+-----+----+----------+--------------+
|                |               |              |
|  API endpoint  |  Broadcaster  |  Storage API |  Communication
|                |               |              |
+----------------+---------------+--------------+

Server layers v2
+------------------------------------------+
|                                          |
|                  Router                  | Traffic routing
|                                          |
+--------------------+---------------------+\
|                                          ||
|               Orchestrator               ||
|                                          ||
+-----------------------+------------------+| Server logic
|cE99                   |                  ||
|     Model instance    |     Companion    ||
|                       |                  ||
+--------------+--------+----+-------------+/
|              |             |             |
| API endpoint | Broadcaster | Storage API |  Communication
|              |             |             |
+--------------+-------------+-------------+

@endditaa