@startditaa
'https://plantuml.com/ditaa

Legend
/----\
|cE99| Model
\----/
/----\
|cADA| View
\----/
/----\
|c9CF|Controller
\----/
/----\
|    | Other
\----/

Client layers
+--------------------------------+
|c9CF                            |
|         Game controller        | Controller
|                                |
+--------------------------------+
|cADA                            |
|          Visualization         |    View
|                                |
+---------------+----------------+
|cADA           |cADA            |
| Event handler | User interface |  Device UI
|               |                |
+---------------+----------------+
|cE99                            |
|          Model mirror          | Client logic
|                                |
+--------------+-----------------+
|              |                 |
|   Receiver   |   Transmitter   | Communication
|              |                 |
+--------------+-----------------+

Server layers v1
+-----------------------------------------------+
|                                               |
|                                               | Traffic routing
|                                               |
+----------+----------+----------+ Orchestrator |
|cE99      |cE99      |cE99      |              |
| Instance | Instance | Instance |              |  Server logic
|          |          |          |              |
+----------+----+-----+----------+--------------+
|               |                |              |
|  Broadcaster  |  API endpoint  |  Storage API |  Communication
|               |                |              |
+---------------+----------------+--------------+

Server layers v2
+------------------------------------------+
|                                          |
|                  Router                  |Traffic routing
|                                          |
+---------------------+--------------------+
|cE99                 |                    |
|    Game instance    |    Orchestrator    | Server logic
|                     |                    |
+-------------+-------+------+-------------+
|             |              |             |
| Broadcaster | API endpoint | Storage API | Communication
|             |              |             |
+-------------+--------------+-------------+

@enduml