@startuml
'https://plantuml.com/class-diagram
'----------------------COMPONENT
legend top left
    |Color| Type |
    |<#physical>| E – Entity|
    |<#lightBlue>| C – Component|
    |<#pink>| S – System|
    |<#darkSeaGreen>| C – Class|
end legend

class BoardPosition << (C, lightBlue) >> {
float x
float y
}
class PathPosition << (C, lightBlue) >> {
int distance
}
class Health << (C, lightBlue) >> {
float health
}
class Money << (C, lightBlue) >> {
float money
}
class Speed << (C, lightBlue) >> {
int speed
}
class Sprite << (C, lightBlue) >> {
String imageName
}
 class Price << (C, lightBlue) >>{
float price
}
class SupportFunction << (C, lightBlue) >> {
function supportFunction
}
class Projectile << (C, lightBlue) >> {
float damage
float cooldown
float cooldownRemaining
float range
bool speedBoost
}
class PlayerTag << (C, lightBlue) >> {
}


'---------------------ENTITY
class AttackTower << (E, physical >>
entity SupportTower << (E, physical >>
entity Enemy << (E, physical >>
entity Player << (E, physical >>

SupportFunction -up-* SupportTower
Price -up-* AttackTower
Price -up-* SupportTower
BoardPosition -up-* AttackTower
BoardPosition -up-* SupportTower
PathPosition -up-* Enemy
Health -up-* Enemy
Health -up-* Player
Sprite -up-* Enemy
Sprite -up-* AttackTower
Sprite -up-* SupportTower
Speed -up-* Enemy
Projectile -up-* AttackTower
Money -up-* Player
PlayerTag -up-* Player

'------------------SYSTEM
class SupportSystem << (S, pink) >>
class ShootingSystem << (S, pink) >>
class RenderSystem << (S, pink) >>
class MovementSystem << (S, pink) >>
class DamagePlayerSystem << (S, pink) >>
class PurchaseSystem << (S, pink) >>

' Enemy archetype
BoardPosition <.. RenderSystem #blue
Sprite <.. RenderSystem #blue
' Tower archetype
PathPosition <.. RenderSystem
Sprite <.. RenderSystem

' Enemy archetype
PathPosition <.. DamagePlayerSystem #blue
' Player archetype
Health <.. DamagePlayerSystem
PlayerTag <.. DamagePlayerSystem

PathPosition <.. MovementSystem
Speed <.. MovementSystem

' Player archetype
Money <.. PurchaseSystem #blue
Price <.. PurchaseSystem

' Support tower archetype
SupportFunction <.. SupportSystem
BoardPosition <.. SupportSystem
' Attack tower archetype
Projectile <.. SupportSystem #blue
BoardPosition <.. SupportSystem #blue

' Attack tower archetype
Projectile <.. ShootingSystem #blue
BoardPosition <.. ShootingSystem #blue
' Enemy archetype
Health <.. ShootingSystem
PathPosition <.. ShootingSystem

'-------------------------------

class Board << (C, darkSeaGreen) >> {
...
}


note right of Board
    Read-only description of
    board.
end note

Board <.up. DamagePlayerSystem
Board <.up. PurchaseSystem
Board <.up. RenderSystem

@enduml