@startuml
'https://plantuml.com/class-diagram

abstract class Component {}
class BoardPosition {
float x
float y
}
class PathPosition {
int distance
}
class Health {
float health
}
class Money {
float money
}
class Speed {
int speed
}
class Sprite {
String imageName
}
class Price {
float price
}
class SupportFunction {
function supportFunction
}
class Projectile {
float damage
float cooldown
float cooldownRemaining
float range
}
class PlayerTag {
}
Component <|-- PlayerTag
Component <|-- PathPosition
Component <|-- SupportFunction
Component <|-- Price
Component <|-- BoardPosition
Component <|-- Health
Component <|-- Sprite
Component <|-- Speed
Component <|-- Projectile
Component <|-- Money

'----------------------------


'----------------------------
abstract class System

System <|-up- RenderSystem
' Enemy archetype
BoardPosition <.. RenderSystem #blue
Sprite <.. RenderSystem #blue
' Tower archetype
PathPosition <.. RenderSystem
Sprite <.. RenderSystem

System <|-up- DamagePlayerSystem
' Enemy archetype
PathPosition <.. DamagePlayerSystem #blue
' Player archetype
Health <.. DamagePlayerSystem
PlayerTag <.. DamagePlayerSystem

System <|-up- MovementSystem
PathPosition <.. MovementSystem
Speed <.. MovementSystem

System <|-up- PurchaseSystem
' Player archetype
Money <.. PurchaseSystem #blue
Price <.. PurchaseSystem

System <|-up- SupportSystem
BoardPosition <.. SupportSystem #blue
SupportFunction <.. SupportSystem

System <|-up- ShootingSystem
' Attack tower archetype
Projectile <.. ShootingSystem #blue
BoardPosition <.. ShootingSystem #blue
' Enemy archetype
Health <.. ShootingSystem
PathPosition <.. ShootingSystem

@enduml