@startuml
'https://plantuml.com/class-diagram

abstract class Component {}
class BoardPosition {
float x
float y
}
class PathPosition {
int distance
}
class Health {
float health
}
class Money {
float money
}
class Speed {
int speed
}
class Sprite {
String imageName
}
class Price {
float price
}
class SupportFunction {
function supportFunction
}
class Projectile {
float damage
float cooldown
float cooldownRemaining
float range
}
class PlayerTag {
}
Component <|-- PlayerTag
Component <|-- PathPosition
Component <|-- SupportFunction
Component <|-- Price
Component <|-- BoardPosition
Component <|-- Health
Component <|-- Sprite
Component <|-- Speed
Component <|-- Projectile
Component <|-- Money

'----------------------------
entity AttackTower
entity SupportTower
entity Enemy
entity Player

SupportFunction --* SupportTower
Price --* AttackTower
Price --* SupportTower
BoardPosition --* AttackTower
BoardPosition --* SupportTower
PathPosition --* Enemy
Health --* Enemy
Health --* Player
Sprite --* Enemy
Sprite --* AttackTower
Sprite --* SupportTower
Speed --* Enemy
Projectile --* AttackTower
Money --* Player
PlayerTag --* Player



'----------------------------

@enduml