@startuml
'https://plantuml.com/sequence-diagram

actor "User" as user
box "Client"
    participant "Event handler" as event
    participant "Visualizer" as visualizer
    participant "Controller" as controller
    participant "Model mirror" as mirror
    participant "API connector" as connector
end box
participant "Server" as server

user -> event : Input

activate event
event -> visualizer : Event is propagated
deactivate event

activate visualizer
note right
    Visualizer interprets
    event as for example a
    board tile being pressed.
end note
visualizer -> controller : Interpreted event
deactivate visualizer

activate controller
note right
    Controller interprets
    event as intent, for
    example placing a
    turret.
end note
controller -> mirror : Intent
deactivate controller

activate mirror
note right
    Model mirror checks if
    intent is valid.
end note
mirror -> connector : Valid change request
deactivate mirror

activate connector
connector -> server
deactivate connector

@enduml