@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true

actor "User" as user
box "Requesting Client"
    participant "User Interface" as ui
    participant "Game Observer" as game
    participant "ApiClient" as connector
    participant "Receiver" as receiver
end box
participant "Server" as server

box "Passive Client"
    participant "Receiver" as receiver2
    participant "Game Observer" as game2
    participant "User Interface" as ui2
    'participant "ApiClient" as connector2

end box
actor "User" as user2

user -> ui : Place tower input

ui -> connector : PlaceTowerRequest()

connector -> server : (Http/s) Endpoint is called

server -> receiver :
&server -> receiver2: (TCP socket) Broadcast sent

receiver -> game: TowerPlacedMessage
&receiver2 -> game2: TowerPlacedMessage

game -> ui : State change
&game2 -> ui2: State Change

ui -> user: :)
&ui2 -> user2:  :O








@enduml