@startuml
'https://plantuml.com/sequence-diagram

actor "User" as user
box "Client"
    participant "Event handler" as event
    participant "User interface" as ui
    participant "Visualizer" as visualizer
    participant "Controller" as controller
    participant "Model mirror" as mirror
end box

user -> event
note right of user
    User starting input
    process that require
    feedback, such as
    drag-and-drop.
end note

activate event
event -> visualizer : Event is propagated
deactivate event

activate visualizer
note right
    Visualizer interprets
    event as for example a
    turret being pressed,
    but not released.
end note
visualizer -> controller : Interpreted event
deactivate visualizer

activate controller
note right
    Controller interprets
    event as intent, for
    example testing if
    a turret placement is
    valid.
end note
controller -> mirror : Intent
deactivate controller

activate mirror
note right
    Model mirror checks if
    intent is valid. Input
    is explicitly part of
    model mirror state,
    so the input in process
    is reported to the
    visualizer.
end note
mirror -> visualizer : Input process
deactivate mirror

activate visualizer
visualizer -> ui : Display process
note right
    Visualizer renders
    input in progress,
    including indicators
    for if it is valid or
    not.
end note
deactivate visualizer

activate ui
ui -> user
deactivate ui

note right of user
    User gets feedback on
    input process has
    information to proceed.
end note

@enduml