@startuml
'https://plantuml.com/component-diagram

package "Server" {
    component "API endpoint" as endpoint
    component "Broadcaster" as broadcaster
    component "Router" as router
    component "Lobby" as lobby
    component "Orchestrator" as orchestrator
    component "Storage API" as storage
    component "Connection Broker" as broker

    orchestrator .up.> broker
    broadcaster ..> broker
    orchestrator .up.> endpoint
    orchestrator .up.> lobby
    orchestrator ..> router
    lobby .up.> router
    lobby .up.> broadcaster
    lobby ..> storage
    router -[hidden]up- broadcaster
    router -[hidden]up- storage
    router .down.> endpoint
    endpoint -[hidden]right- broadcaster
    broadcaster -[hidden]right- storage
}

package "Client" {
    component GameObserver
    component UserInterface
    component "Receiver" as receiver
    component "API connector" as connector

    GameObserver ..> receiver
    UserInterface ..> GameObserver
    UserInterface ..> connector
    GameObserver ..> connector
}

receiver ..> broadcaster
connector ..> endpoint

@enduml