@startuml
'https://plantuml.com/component-diagram

package "Server" {
    component "API endpoint" as endpoint
    component "Broadcaster" as broadcaster
    component "Router" as router
    component "Model instance" as model
    component "Orchestrator" as orchestrator
    component "Storage API" as storage

    orchestrator .up.> endpoint
    orchestrator .up.> model
    orchestrator .up.> storage
    model .up.> router
    model .up.> broadcaster
    model .up.> storage
    router -[hidden]up- broadcaster
    router -[hidden]up- storage
    router .down.> endpoint
    endpoint -[hidden]right- broadcaster
    broadcaster -[hidden]right- storage
}

package "Client" {
    component "Event handler" as event
    component "Game controller" as controller
    component "Model mirror" as mirror
    component "Receiver" as receiver
    component "API connector" as connector
    component "Visualizer" as visualizer
    component "User interface" as ui

    controller .down.> visualizer
    controller .down.> mirror
    visualizer .down.> event
    visualizer .down.> mirror
    visualizer -[hidden]down- receiver
    visualizer .down.> ui
    event -[hidden]- mirror
    event -[hidden]- receiver
    event -[hidden]- connector
    ui -[hidden]- mirror
    ui -[hidden]- receiver
    ui -[hidden]- connector
    mirror ..> connector
    mirror ..> receiver
}

receiver ..> broadcaster
connector ..> endpoint

@enduml