@startuml
'https://plantuml.com/component-diagram

package "Server" {
    component "API endpoint" as endpoint
    component "Broadcaster" as broadcaster
    component "Model instance" as model
    component "Orchestrator" as orchestrator
    component "Storage API" as storage

    orchestrator -up-> endpoint
    orchestrator -up-> model
    orchestrator -up-> storage
    model -[hidden]up-> endpoint
    model -up-> broadcaster
    model -[hidden]up-> storage
}

package "Client" {
    component "Event handler" as event
    component "Game controller" as controller
    component "Model mirror" as mirror
    component "Receiver" as receiver
    component "API connector" as connector
    component "Visualization" as visualization
    component "User interface" as ui

    controller -down-> visualization
    controller -down-> connector
    visualization -[hidden]down-> receiver
    visualization -down-> event
    visualization -down-> ui
    visualization -down-> mirror
    event -[hidden]-> mirror
    event -[hidden]-> receiver
    event -[hidden]-> connector
    ui -[hidden]-> mirror
    ui -[hidden]-> receiver
    ui -[hidden]-> connector
    mirror -[hidden]-> connector
    mirror --> receiver
}

receiver --> broadcaster
connector --> endpoint

@enduml