@startuml
'https://plantuml.com/deployment-diagram

node "Android > 4.0" <<Android Client>> {
    package game as "game.apk"
}

cloud "Google Cloud Platform" #DodgerBlue;line:White;text:White {
    node "Debian GNU/Linux 10" <<VM instance>> #White {
        package backend [
            .NET back-end
        ]
    }

    database firestore [

----
GCP Cloud Storage
----

    ]

    backend -[thickness=2]- firestore
}

backend -[thickness=4]right- game : "            Internet          "
backend <.right. game : "             "

@enduml