@startuml
'https://plantuml.com/deployment-diagram

node "Android > 4.0" <<Android Client>> {
    package game as "game.apk"
}
node "Development computer" #White {
    package backend [
        .NET back-end
    ]
}

cloud "Google Cloud Platform" #DodgerBlue;line:White;text:White {

    database firestore [

----
GCP Cloud Storage
----

    ]

    backend <..> firestore : "HTTP/S"
}

backend -[thickness=4]right- game : "            TCP Socket         "
backend <.right. game : "      HTTP/S       "

@enduml